//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace application
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComputerShopEntities : DbContext
    {
        public ComputerShopEntities()
            : base("name=ComputerShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts_> Accounts_ { get; set; }
        public virtual DbSet<Baskets_> Baskets_ { get; set; }
        public virtual DbSet<Baskets_Products> Baskets_Products { get; set; }
        public virtual DbSet<Baskets_Services> Baskets_Services { get; set; }
        public virtual DbSet<Clients_> Clients_ { get; set; }
        public virtual DbSet<Masters_> Masters_ { get; set; }
        public virtual DbSet<Masters_Services> Masters_Services { get; set; }
        public virtual DbSet<Orders_> Orders_ { get; set; }
        public virtual DbSet<Products_> Products_ { get; set; }
        public virtual DbSet<Roles_> Roles_ { get; set; }
        public virtual DbSet<Services_> Services_ { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
